// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameworkStudents.Migrations
{
    [DbContext(typeof(UniversityContext))]
    [Migration("20221109143728_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rocnik")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jmeno = "Bohdan",
                            Rocnik = 2
                        },
                        new
                        {
                            Id = 2,
                            Jmeno = "Hubert",
                            Rocnik = 2
                        },
                        new
                        {
                            Id = 3,
                            Jmeno = "Alena",
                            Rocnik = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
